services:
  - type: worker
    name: DreamxBotz
    env: python
    region: oregon
    plan: free
    startCommand: python3 bot.py
    buildCommand: pip install -r requirements.txt
    autoDeploy: true
    
